### ISSUE TITLE
Segmentation fault with query --count

### ISSUE THREAD

**Issue by lh3** [mohsenzakeri/Movi#15]
I am counting 125bp short reads in the attached against the 100-human index you kindly sent me earlier. The command line I am using is:
```sh
movi-default query --count -i human100 -r movi-bug.fa.gz
```
Option `--pml` works on this file. Could you try and see if you can reproduce the issue? Thanks.

[movi-bug.fa.gz](https://github.com/user-attachments/files/16594392/movi-bug.fa.gz)

**Comment by mohsenzakeri** [comment]
Hi @lh3,

Thank you for your message. Based on the command you have specified; I'm assuming you are using the latest version of the code on the main branch. I believe the main reason for the segmentation fault was the existence of non-ACGT characters in the reads. I just pushed a bugfix commit to the main branch to resolve this issue. Please let me know if this update works for you. Thanks again for bringing this issue to my attention.

Best,
Mohsen

**Comment by lh3** [comment]
Thanks for the quick fix. Yes, I am on the "main" branch and the update fixed the bug. I am closing this now.

Relatedly, I guess `--count` outputs the occurrence of the longest matching suffix via backward search. Is it right? I noticed that `--pml` is several times faster than `--count` on the same input. Is it expected?

Also, is the "develop" faster and/or does it have more functionality? If I want to play with movi ultimately for preprint, would you recommend to use the "develop" branch instead? Thanks.

**Comment by mohsenzakeri** [comment]
Hi again @lh3, I'm glad to hear that your problem was resolved.  The count query finds the length of the longest exact match from the end of the query via backward search and also computes the number of occurrences of that exact match.  If there is mismatch at the middle of the read the query stops, while the PML query processes the whole read no matter what.  This might suggest that the count query should actually be faster.  However, in order to find the number of occurrences (something that is not required for the PML queries), we have to do a linear scan on all the runs in the final interval (because currently we don't keep any global BWT offset in the rows of Movi table).  This is not a huge problem in most of the cases, but I found that there are pathological cases that makes the linear scan very expensive.  For example, if the backward search stops after a few bases because of the encounter of an `N`, i.e. after 3 bases, the interval at that point is huge and comparable to the size of the table (r), so the count query scans almost all the rows in the table to compute the actual count.  Potentially for your case, if you remove all non-ACGT bases (specially `N` bases) from the reads, you will observe a higher speed for the count query.

We have implemented a new compact version of the index in the develop branch which is both smaller and also uses a lot of optimizations to a avoid issues like the one I described above.  For example, we are using a `ftab` with small `k` (k <=12) to accelerate the backward search. The `ftab` stores the result of the count query for all possible strings of size k and is very small compared to the size of the index (but it needs a small tweak to be ready for this specific application). If you are interested, I can build the compact index for you and show how you can run the queries with the develop branch.

**Comment by mohsenzakeri** [comment]
Hi again, as an alternative solution for handling reads containing non-ACGT characters, I have added a new flag to the main branch: --ignore-illegal-chars <value>.

Setting this flag to 1 substitutes any illegal character with A, while setting it to 2 will substitute any illegal character with a randomly selected character from the alphabet. Both options seem to improve performance. However, setting it to 1 is preferable for obtaining consistent count results from the same input.

I would really appreciate it if let me know if you observe any significant performance difference using this flag.

**Comment by lh3** [comment]
Thanks. Adding the option is indeed faster by a factor of ~3.

**Comment by mohsenzakeri** [comment]
Hi again @lh3,

I'm glad to hear about the speed improvement. I also wanted to let you know that I've moved some of the latest changes from the `develop` branch to `main` and created a new [tagged version](https://github.com/mohsenzakeri/Movi/releases/tag/v1.1.0).

The index size in this version is about 40% smaller. The reduction, along with other improvements, has led to speed enhancements as well. You might be interested in using this version for your benchmarks. You can download the new index from [here](https://livejohnshopkins-my.sharepoint.com/:f:/g/personal/mzakeri1_jh_edu/ElcKe_fh9OBChzQ2DFHoNwQBN0syQwmQ6kfXx6tMyUhb0w?e=rl37qh).

If you'd like to try using `ftab` for backward search queries, you can build the ftab by running:  
`movi-default ftab --index <index_dir> --ftab-k <n>`.  
A reasonable value for `n` is between 10 and 12.  
To use the `ftab`, add `--ftab-k <n>` to the query command.

Best,  
Mohsen

**Comment by lh3** [comment]
Thanks a lot for the update. Run on the same machine, the new version is about 10% faster on PML. Nonetheless, due to complications on our cluster (cluster nodes all have the same hardware but the running time differ a lot), I couldn't reproduce the shortest timing with the old version. In the ropebwt3 manuscript, which I have just submitted as I won't have much time when new semester starts, I am reporting the smaller peak memory with the new version and the fastest speed I have recorded so far. I will rerun Movi later during revision to see if I can get more stable timing. I tried ftab with PML (not with backward search). It seems that this option does not affect PML. Is that right?

I briefly read the Movi source code. Based on what I understand, the new strategy is eye opening and I think future tools should use it. Just two quick questions: 1) you are using `uint32_t` to store the run id. That is just enough for the 100 human genomes. Will you use bit packing for larger pangenomes? 2) how do you store the base A/C/G/T of a run? Do you bit-pack it to a variable on a row?

**Comment by mohsenzakeri** [comment]
I'm glad to hear that you found the new index useful, and you used it in the benchmarks. I briefly read the manuscript you mentioned, and it was really interesting. I found the incremental BWT construction very useful, especially as it significantly reduces the construction memory and potentially makes the index updatable. I also really appreciate the acknowledgment in the manuscript.

I confirm that the `ftab` is not useful for the PMLs and it is only used for count and ZML queries. To answer to your other questions:

1) We have reserved 5 bytes to store the run id: one `uint32_t` and 8 bits of another `uint16_t` variable (`overflow_bits `). As you said, `uint32_t` is not enough for 100 human genomes.
2) We store the character at the most significant bits of the `thresholds_status` variable. The `end` or `$` row is identified by storing its index explicitly. Currently, we do not use separators between the genomes.
3) We use additional bits as flags for overflowing `n` ,`offset`, and `threshold`. In the case of overflow for each the values are stored in separate vectors of `uint64_t`s.

More details about the bits are found here: https://github.com/mohsenzakeri/Movi/blob/main/include/move_row.hpp#L12-L20

Please let me know if you have any more questions or suggestions.

**Comment by lh3** [comment]
Thanks a lot for the explanation. As Movi can do backward search and it already stores both strands by default, it should not be hard to support forward search and SMEM finding. Travis Gagie pointed me to [b-move](https://github.com/biointec/b-move), but based on the numbers in the paper, I guess its data structure is closer to the old Movi. You probably know more than me as you are also acknowledged in that paper :-)

**Comment by mohsenzakeri** [comment]
I agree that implementing the SMEM finding in Movi is possible and it is something that I will try to implement soon. Thanks for the nice tip. :)
